/*The dataset bigquery-public-data.google_analytics_sample.ga_sessions_20170801 contains session-level data from the Google Merchandise
 Store, which includes information on user interactions with the website. */
 

-- 1. Traffic Sources
-- This query identifies the distribution of traffic sources for sessions on the specified date.
SELECT
  trafficSource.source AS source,
  trafficSource.medium AS medium,
  COUNT(*) AS session_count
FROM
  `bigquery-public-data.google_analytics_sample.ga_sessions_20170801`
GROUP BY
  source, medium
ORDER BY
  session_count DESC
LIMIT 100;

-- 2. Analyze Device Categories for  Traffic
-- This query provides insights into which devices were most commonly used by users who came via  campaigns.

SELECT
  device.deviceCategory AS device_category,
  COUNT(*) AS session_count,
  SUM(totals.totalTransactionRevenue) / 1e6 AS total_revenue_usd
FROM
  `bigquery-public-data.google_analytics_sample.ga_sessions_20170801`

GROUP BY
  device_category
ORDER BY
  session_count DESC
LIMIT 100;

-- 3. User Location Analysis for PPC Traffic
-- This query analyzes the geographic distribution of users who came via PPC campaigns.

SELECT
  geoNetwork.country AS country,
  COUNT(*) AS session_count,
  SUM(totals.totalTransactionRevenue) / 1e6 AS total_revenue_usd
FROM
  `bigquery-public-data.google_analytics_sample.ga_sessions_20170801`

GROUP BY
  country
ORDER BY
  session_count DESC
LIMIT 100;

-- 4. Customer Lifetime Value (CLV) Calculation
-- This query estimates the customer lifetime value by calculating the total revenue generated by a visitor across multiple sessions.
WITH
  customer_revenue AS (
    SELECT
      fullVisitorId,
      SUM(totals.totalTransactionRevenue) / 1e6 AS total_revenue_usd
    FROM
      `bigquery-public-data.google_analytics_sample.ga_sessions_20170801`
    GROUP BY
      fullVisitorId
  )

SELECT
  total_revenue_usd,
  COUNT(*) AS number_of_customers
FROM
  customer_revenue
GROUP BY
  total_revenue_usd
ORDER BY
  total_revenue_usd DESC
LIMIT 100;


-- 5. Day of Week and Hour of Day Analysis for PPC Traffic
-- This query analyzes when PPC traffic is most active by looking at the day of the week and hour of the day.

-- formula 1e6 to decrease the value for a smaller number

SELECT
  EXTRACT(DAYOFWEEK FROM TIMESTAMP_SECONDS(visitStartTime)) AS day_of_week,
  EXTRACT(HOUR FROM TIMESTAMP_SECONDS(visitStartTime)) AS hour_of_day,
  COUNT(*) AS session_count,
  SUM(totals.totalTransactionRevenue) / 1e6 AS total_revenue_usd
FROM
  `bigquery-public-data.google_analytics_sample.ga_sessions_20170801`

GROUP BY
  day_of_week, hour_of_day
ORDER BY
  total_revenue_usd DESC
LIMIT 100;


-- 6.  Traffic Sources Analysis
-- This query identifies the top sources driving traffic to your site, which can help understand where your marketing efforts are most effective.
SELECT 
  trafficSource.source AS traffic_source,
  COUNT(*) AS session_count,
  AVG(totals.pageviews) AS avg_pageviews_per_session
FROM 
  `bigquery-public-data.google_analytics_sample.ga_sessions_20170801`
GROUP BY 
  traffic_source
ORDER BY 
  session_count DESC


-- 7. Behavior by Device Category
-- This query reveals how different devices contribute to sessions, which is crucial for optimizing marketing campaigns across platforms.
SELECT 
  device.deviceCategory AS device_category,
  COUNT(*) AS session_count,
  AVG(totals.pageviews) AS avg_pageviews_per_session,
FROM 
  `bigquery-public-data.google_analytics_sample.ga_sessions_20170801`
GROUP BY 
  device_category
ORDER BY 
  session_count DESC

-- 8. User Engagement by Hour
-- This query helps understand when users are most active, which can inform the timing of your marketing activities.

SELECT 
  trafficSource.source as source,
  EXTRACT(HOUR FROM TIMESTAMP_SECONDS(visitStartTime)) AS hour,
  COUNT(*) AS session_count,
  AVG(totals.pageviews) AS avg_pageviews_per_session
FROM 
  `bigquery-public-data.google_analytics_sample.ga_sessions_20170801`
GROUP BY 
  trafficSource.source, hour
ORDER BY 
  2


-- 9. New vs. Returning Visitors

-- This query differentiates between new and returning visitors, helping to evaluate the effectiveness of retention strategies.
-- used condition - if(condition, if true, if false)
SELECT 
  trafficSource.source as source,
    EXTRACT(HOUR FROM TIMESTAMP_SECONDS(visitStartTime)) AS hour,
  IF(visitNumber = 1, 'New Visitor', 'Returning Visitor') AS visitor_type,
  COUNT(*) AS session_count
FROM 
  `bigquery-public-data.google_analytics_sample.ga_sessions_20170801`
GROUP BY 
  1, 2,3
order by
1 asc, 2 desc
